name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the api Docker image
      run: docker build -t boticot/api:0.8.0-alpha ./api
    - name: Login to Docker regitry
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PWD}}
    - name: Push api to Docker regitry
      run: docker push boticot/api:0.8.0-alpha
      
